# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_IP_Phone_Tester.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IP_Phone_Tester(object):
    def setupUi(self, IP_Phone_Tester):
        IP_Phone_Tester.setObjectName("IP_Phone_Tester")
        IP_Phone_Tester.resize(570, 407)
        IP_Phone_Tester.setMinimumSize(QtCore.QSize(383, 0))
        IP_Phone_Tester.setMaximumSize(QtCore.QSize(1000, 629))
        IP_Phone_Tester.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("touchscreen.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("touchscreen.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        IP_Phone_Tester.setWindowIcon(icon)
        IP_Phone_Tester.setAnimated(True)
        IP_Phone_Tester.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(IP_Phone_Tester)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_Baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Baudrate.setGeometry(QtCore.QRect(89, 28, 74, 20))
        self.comboBox_Baudrate.setObjectName("comboBox_Baudrate")
        self.comboBox_COM = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_COM.setGeometry(QtCore.QRect(9, 28, 74, 20))
        self.comboBox_COM.setObjectName("comboBox_COM")
        self.label_change_port = QtWidgets.QLabel(self.centralwidget)
        self.label_change_port.setGeometry(QtCore.QRect(9, 9, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_change_port.setFont(font)
        self.label_change_port.setObjectName("label_change_port")
        self.pushButton_open_COM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_COM.setGeometry(QtCore.QRect(169, 27, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_open_COM.setFont(font)
        self.pushButton_open_COM.setObjectName("pushButton_open_COM")
        self.pushButton_Speak = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Speak.setEnabled(False)
        self.pushButton_Speak.setGeometry(QtCore.QRect(220, 340, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Speak.setFont(font)
        self.pushButton_Speak.setCheckable(True)
        self.pushButton_Speak.setObjectName("pushButton_Speak")
        self.pushButton_close_COM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close_COM.setEnabled(False)
        self.pushButton_close_COM.setGeometry(QtCore.QRect(265, 27, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_close_COM.setFont(font)
        self.pushButton_close_COM.setObjectName("pushButton_close_COM")
        self.pushButton_Hendset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Hendset.setEnabled(False)
        self.pushButton_Hendset.setGeometry(QtCore.QRect(220, 310, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Hendset.setFont(font)
        self.pushButton_Hendset.setCheckable(True)
        self.pushButton_Hendset.setObjectName("pushButton_Hendset")
        self.pushButton_Mic = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Mic.setEnabled(False)
        self.pushButton_Mic.setGeometry(QtCore.QRect(400, 310, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Mic.setFont(font)
        self.pushButton_Mic.setCheckable(True)
        self.pushButton_Mic.setObjectName("pushButton_Mic")
        self.frame_LED = QtWidgets.QFrame(self.centralwidget)
        self.frame_LED.setGeometry(QtCore.QRect(10, 60, 201, 311))
        self.frame_LED.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_LED.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_LED.setObjectName("frame_LED")
        self.checkBox_1 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_1.setEnabled(False)
        self.checkBox_1.setGeometry(QtCore.QRect(15, 30, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_1.setFont(font)
        self.checkBox_1.setObjectName("checkBox_1")
        self.label_main = QtWidgets.QLabel(self.frame_LED)
        self.label_main.setGeometry(QtCore.QRect(50, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_main.setFont(font)
        self.label_main.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_main.setStyleSheet("")
        self.label_main.setObjectName("label_main")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setGeometry(QtCore.QRect(15, 50, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setGeometry(QtCore.QRect(15, 70, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setGeometry(QtCore.QRect(15, 90, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_5.setEnabled(False)
        self.checkBox_5.setGeometry(QtCore.QRect(15, 110, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_6.setEnabled(False)
        self.checkBox_6.setGeometry(QtCore.QRect(15, 130, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_7.setEnabled(False)
        self.checkBox_7.setGeometry(QtCore.QRect(15, 150, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_8.setEnabled(False)
        self.checkBox_8.setGeometry(QtCore.QRect(15, 170, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_9.setEnabled(False)
        self.checkBox_9.setGeometry(QtCore.QRect(15, 190, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_10.setEnabled(False)
        self.checkBox_10.setGeometry(QtCore.QRect(15, 210, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_11.setEnabled(False)
        self.checkBox_11.setGeometry(QtCore.QRect(75, 30, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_12.setEnabled(False)
        self.checkBox_12.setGeometry(QtCore.QRect(75, 50, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_13.setEnabled(False)
        self.checkBox_13.setGeometry(QtCore.QRect(75, 70, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_14.setEnabled(False)
        self.checkBox_14.setGeometry(QtCore.QRect(75, 90, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_15.setEnabled(False)
        self.checkBox_15.setGeometry(QtCore.QRect(75, 110, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_16.setEnabled(False)
        self.checkBox_16.setGeometry(QtCore.QRect(75, 130, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_16.setFont(font)
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_17.setEnabled(False)
        self.checkBox_17.setGeometry(QtCore.QRect(75, 150, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_17.setFont(font)
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_18.setEnabled(False)
        self.checkBox_18.setGeometry(QtCore.QRect(75, 170, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_18.setFont(font)
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_19.setEnabled(False)
        self.checkBox_19.setGeometry(QtCore.QRect(75, 190, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_19.setFont(font)
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_20.setEnabled(False)
        self.checkBox_20.setGeometry(QtCore.QRect(75, 210, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_20.setFont(font)
        self.checkBox_20.setObjectName("checkBox_20")
        self.checkBox_21 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_21.setEnabled(False)
        self.checkBox_21.setGeometry(QtCore.QRect(135, 30, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_21.setFont(font)
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_22 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_22.setEnabled(False)
        self.checkBox_22.setGeometry(QtCore.QRect(135, 50, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_22.setFont(font)
        self.checkBox_22.setObjectName("checkBox_22")
        self.checkBox_23 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_23.setEnabled(False)
        self.checkBox_23.setGeometry(QtCore.QRect(135, 70, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_23.setFont(font)
        self.checkBox_23.setObjectName("checkBox_23")
        self.checkBox_24 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_24.setEnabled(False)
        self.checkBox_24.setGeometry(QtCore.QRect(135, 90, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_24.setFont(font)
        self.checkBox_24.setObjectName("checkBox_24")
        self.checkBox_25 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_25.setEnabled(False)
        self.checkBox_25.setGeometry(QtCore.QRect(135, 110, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_25.setFont(font)
        self.checkBox_25.setObjectName("checkBox_25")
        self.checkBox_26 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_26.setEnabled(False)
        self.checkBox_26.setGeometry(QtCore.QRect(135, 130, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_26.setFont(font)
        self.checkBox_26.setObjectName("checkBox_26")
        self.checkBox_27 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_27.setEnabled(False)
        self.checkBox_27.setGeometry(QtCore.QRect(135, 150, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_27.setFont(font)
        self.checkBox_27.setObjectName("checkBox_27")
        self.checkBox_28 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_28.setEnabled(False)
        self.checkBox_28.setGeometry(QtCore.QRect(135, 170, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_28.setFont(font)
        self.checkBox_28.setObjectName("checkBox_28")
        self.checkBox_29 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_29.setEnabled(False)
        self.checkBox_29.setGeometry(QtCore.QRect(135, 190, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_29.setFont(font)
        self.checkBox_29.setObjectName("checkBox_29")
        self.checkBox_30 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_30.setEnabled(False)
        self.checkBox_30.setGeometry(QtCore.QRect(135, 210, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_30.setFont(font)
        self.checkBox_30.setObjectName("checkBox_30")
        self.pushButton_Next_LED = QtWidgets.QPushButton(self.frame_LED)
        self.pushButton_Next_LED.setEnabled(False)
        self.pushButton_Next_LED.setGeometry(QtCore.QRect(15, 250, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Next_LED.setFont(font)
        self.pushButton_Next_LED.setObjectName("pushButton_Next_LED")
        self.pushButton_LED_1 = QtWidgets.QPushButton(self.frame_LED)
        self.pushButton_LED_1.setEnabled(False)
        self.pushButton_LED_1.setGeometry(QtCore.QRect(10, 280, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_LED_1.setFont(font)
        self.pushButton_LED_1.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_LED_1.setCheckable(True)
        self.pushButton_LED_1.setObjectName("pushButton_LED_1")
        self.pushButton_LED_2 = QtWidgets.QPushButton(self.frame_LED)
        self.pushButton_LED_2.setEnabled(False)
        self.pushButton_LED_2.setGeometry(QtCore.QRect(100, 280, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_LED_2.setFont(font)
        self.pushButton_LED_2.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_LED_2.setCheckable(True)
        self.pushButton_LED_2.setObjectName("pushButton_LED_2")
        self.radioButton_Perm = QtWidgets.QRadioButton(self.frame_LED)
        self.radioButton_Perm.setEnabled(False)
        self.radioButton_Perm.setGeometry(QtCore.QRect(10, 230, 121, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_Perm.setFont(font)
        self.radioButton_Perm.setObjectName("radioButton_Perm")
        self.radioButton_Blink = QtWidgets.QRadioButton(self.frame_LED)
        self.radioButton_Blink.setEnabled(False)
        self.radioButton_Blink.setGeometry(QtCore.QRect(110, 230, 91, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_Blink.setFont(font)
        self.radioButton_Blink.setObjectName("radioButton_Blink")
        self.frame_Key = QtWidgets.QFrame(self.centralwidget)
        self.frame_Key.setGeometry(QtCore.QRect(220, 60, 341, 241))
        self.frame_Key.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Key.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Key.setObjectName("frame_Key")
        self.frame_9 = QtWidgets.QFrame(self.frame_Key)
        self.frame_9.setGeometry(QtCore.QRect(10, 190, 101, 20))
        self.frame_9.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_t9 = QtWidgets.QLabel(self.frame_9)
        self.label_t9.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t9.setFont(font)
        self.label_t9.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t9.setStyleSheet("")
        self.label_t9.setObjectName("label_t9")
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        self.label_9.setGeometry(QtCore.QRect(13, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.frame_4 = QtWidgets.QFrame(self.frame_Key)
        self.frame_4.setGeometry(QtCore.QRect(10, 90, 101, 20))
        self.frame_4.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_t4 = QtWidgets.QLabel(self.frame_4)
        self.label_t4.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t4.setFont(font)
        self.label_t4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t4.setStyleSheet("")
        self.label_t4.setObjectName("label_t4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(13, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.frame_8 = QtWidgets.QFrame(self.frame_Key)
        self.frame_8.setGeometry(QtCore.QRect(10, 170, 101, 20))
        self.frame_8.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_t8 = QtWidgets.QLabel(self.frame_8)
        self.label_t8.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t8.setFont(font)
        self.label_t8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t8.setStyleSheet("")
        self.label_t8.setObjectName("label_t8")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setGeometry(QtCore.QRect(13, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.frame_3 = QtWidgets.QFrame(self.frame_Key)
        self.frame_3.setGeometry(QtCore.QRect(10, 70, 101, 20))
        self.frame_3.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_t3 = QtWidgets.QLabel(self.frame_3)
        self.label_t3.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t3.setFont(font)
        self.label_t3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t3.setStyleSheet("")
        self.label_t3.setObjectName("label_t3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(12, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.frame_1 = QtWidgets.QFrame(self.frame_Key)
        self.frame_1.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.frame_1.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.label_t1 = QtWidgets.QLabel(self.frame_1)
        self.label_t1.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t1.setFont(font)
        self.label_t1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t1.setStyleSheet("")
        self.label_t1.setObjectName("label_t1")
        self.label_1 = QtWidgets.QLabel(self.frame_1)
        self.label_1.setGeometry(QtCore.QRect(12, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_1.setStyleSheet("")
        self.label_1.setObjectName("label_1")
        self.frame_10 = QtWidgets.QFrame(self.frame_Key)
        self.frame_10.setGeometry(QtCore.QRect(10, 210, 101, 20))
        self.frame_10.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_t10 = QtWidgets.QLabel(self.frame_10)
        self.label_t10.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t10.setFont(font)
        self.label_t10.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t10.setStyleSheet("")
        self.label_t10.setObjectName("label_t10")
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        self.label_10.setGeometry(QtCore.QRect(13, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.frame_6 = QtWidgets.QFrame(self.frame_Key)
        self.frame_6.setGeometry(QtCore.QRect(10, 130, 101, 20))
        self.frame_6.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_t6 = QtWidgets.QLabel(self.frame_6)
        self.label_t6.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t6.setFont(font)
        self.label_t6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t6.setStyleSheet("")
        self.label_t6.setObjectName("label_t6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(13, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.frame_2 = QtWidgets.QFrame(self.frame_Key)
        self.frame_2.setGeometry(QtCore.QRect(10, 50, 101, 20))
        self.frame_2.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_t2 = QtWidgets.QLabel(self.frame_2)
        self.label_t2.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t2.setFont(font)
        self.label_t2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t2.setStyleSheet("")
        self.label_t2.setObjectName("label_t2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(12, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_Key)
        self.frame_5.setGeometry(QtCore.QRect(10, 110, 101, 20))
        self.frame_5.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_t5 = QtWidgets.QLabel(self.frame_5)
        self.label_t5.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t5.setFont(font)
        self.label_t5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t5.setStyleSheet("")
        self.label_t5.setObjectName("label_t5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(13, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.frame_7 = QtWidgets.QFrame(self.frame_Key)
        self.frame_7.setGeometry(QtCore.QRect(10, 150, 101, 20))
        self.frame_7.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_t7 = QtWidgets.QLabel(self.frame_7)
        self.label_t7.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t7.setFont(font)
        self.label_t7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t7.setStyleSheet("")
        self.label_t7.setObjectName("label_t7")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(13, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.frame_13 = QtWidgets.QFrame(self.frame_Key)
        self.frame_13.setGeometry(QtCore.QRect(120, 70, 101, 20))
        self.frame_13.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_t13 = QtWidgets.QLabel(self.frame_13)
        self.label_t13.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t13.setFont(font)
        self.label_t13.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t13.setStyleSheet("")
        self.label_t13.setObjectName("label_t13")
        self.label_13 = QtWidgets.QLabel(self.frame_13)
        self.label_13.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.frame_18 = QtWidgets.QFrame(self.frame_Key)
        self.frame_18.setGeometry(QtCore.QRect(120, 170, 101, 20))
        self.frame_18.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_t18 = QtWidgets.QLabel(self.frame_18)
        self.label_t18.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t18.setFont(font)
        self.label_t18.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t18.setStyleSheet("")
        self.label_t18.setObjectName("label_t18")
        self.label_18 = QtWidgets.QLabel(self.frame_18)
        self.label_18.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_18.setStyleSheet("")
        self.label_18.setObjectName("label_18")
        self.frame_11 = QtWidgets.QFrame(self.frame_Key)
        self.frame_11.setGeometry(QtCore.QRect(120, 30, 101, 20))
        self.frame_11.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_t11 = QtWidgets.QLabel(self.frame_11)
        self.label_t11.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t11.setFont(font)
        self.label_t11.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t11.setStyleSheet("")
        self.label_t11.setObjectName("label_t11")
        self.label_11 = QtWidgets.QLabel(self.frame_11)
        self.label_11.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.frame_19 = QtWidgets.QFrame(self.frame_Key)
        self.frame_19.setGeometry(QtCore.QRect(120, 190, 101, 20))
        self.frame_19.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.label_t19 = QtWidgets.QLabel(self.frame_19)
        self.label_t19.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t19.setFont(font)
        self.label_t19.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t19.setStyleSheet("")
        self.label_t19.setObjectName("label_t19")
        self.label_19 = QtWidgets.QLabel(self.frame_19)
        self.label_19.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_19.setStyleSheet("")
        self.label_19.setObjectName("label_19")
        self.frame_15 = QtWidgets.QFrame(self.frame_Key)
        self.frame_15.setGeometry(QtCore.QRect(120, 110, 101, 20))
        self.frame_15.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_t15 = QtWidgets.QLabel(self.frame_15)
        self.label_t15.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t15.setFont(font)
        self.label_t15.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t15.setStyleSheet("")
        self.label_t15.setObjectName("label_t15")
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        self.label_15.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.frame_12 = QtWidgets.QFrame(self.frame_Key)
        self.frame_12.setGeometry(QtCore.QRect(120, 50, 101, 20))
        self.frame_12.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_t12 = QtWidgets.QLabel(self.frame_12)
        self.label_t12.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t12.setFont(font)
        self.label_t12.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t12.setStyleSheet("")
        self.label_t12.setObjectName("label_t12")
        self.label_12 = QtWidgets.QLabel(self.frame_12)
        self.label_12.setGeometry(QtCore.QRect(10, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.frame_14 = QtWidgets.QFrame(self.frame_Key)
        self.frame_14.setGeometry(QtCore.QRect(120, 90, 101, 20))
        self.frame_14.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_t14 = QtWidgets.QLabel(self.frame_14)
        self.label_t14.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t14.setFont(font)
        self.label_t14.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t14.setStyleSheet("")
        self.label_t14.setObjectName("label_t14")
        self.label_14 = QtWidgets.QLabel(self.frame_14)
        self.label_14.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.frame_16 = QtWidgets.QFrame(self.frame_Key)
        self.frame_16.setGeometry(QtCore.QRect(120, 130, 101, 20))
        self.frame_16.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_t16 = QtWidgets.QLabel(self.frame_16)
        self.label_t16.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t16.setFont(font)
        self.label_t16.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t16.setStyleSheet("")
        self.label_t16.setObjectName("label_t16")
        self.label_16 = QtWidgets.QLabel(self.frame_16)
        self.label_16.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.frame_20 = QtWidgets.QFrame(self.frame_Key)
        self.frame_20.setGeometry(QtCore.QRect(120, 210, 101, 20))
        self.frame_20.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_t20 = QtWidgets.QLabel(self.frame_20)
        self.label_t20.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t20.setFont(font)
        self.label_t20.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t20.setStyleSheet("")
        self.label_t20.setObjectName("label_t20")
        self.label_20 = QtWidgets.QLabel(self.frame_20)
        self.label_20.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_20.setStyleSheet("")
        self.label_20.setObjectName("label_20")
        self.frame_17 = QtWidgets.QFrame(self.frame_Key)
        self.frame_17.setGeometry(QtCore.QRect(120, 150, 101, 20))
        self.frame_17.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_t17 = QtWidgets.QLabel(self.frame_17)
        self.label_t17.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t17.setFont(font)
        self.label_t17.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t17.setStyleSheet("")
        self.label_t17.setObjectName("label_t17")
        self.label_17 = QtWidgets.QLabel(self.frame_17)
        self.label_17.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_17.setStyleSheet("")
        self.label_17.setObjectName("label_17")
        self.frame_23 = QtWidgets.QFrame(self.frame_Key)
        self.frame_23.setGeometry(QtCore.QRect(230, 70, 101, 20))
        self.frame_23.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_23.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.label_t23 = QtWidgets.QLabel(self.frame_23)
        self.label_t23.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t23.setFont(font)
        self.label_t23.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t23.setStyleSheet("")
        self.label_t23.setObjectName("label_t23")
        self.label_23 = QtWidgets.QLabel(self.frame_23)
        self.label_23.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_23.setStyleSheet("")
        self.label_23.setObjectName("label_23")
        self.frame_28 = QtWidgets.QFrame(self.frame_Key)
        self.frame_28.setGeometry(QtCore.QRect(230, 170, 101, 20))
        self.frame_28.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_28.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.label_t28 = QtWidgets.QLabel(self.frame_28)
        self.label_t28.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t28.setFont(font)
        self.label_t28.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t28.setStyleSheet("")
        self.label_t28.setObjectName("label_t28")
        self.label_24 = QtWidgets.QLabel(self.frame_28)
        self.label_24.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_24.setStyleSheet("")
        self.label_24.setObjectName("label_24")
        self.frame_25 = QtWidgets.QFrame(self.frame_Key)
        self.frame_25.setGeometry(QtCore.QRect(230, 110, 101, 20))
        self.frame_25.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_25.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.label_t25 = QtWidgets.QLabel(self.frame_25)
        self.label_t25.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t25.setFont(font)
        self.label_t25.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t25.setStyleSheet("")
        self.label_t25.setObjectName("label_t25")
        self.label_25 = QtWidgets.QLabel(self.frame_25)
        self.label_25.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_25.setStyleSheet("")
        self.label_25.setObjectName("label_25")
        self.frame_27 = QtWidgets.QFrame(self.frame_Key)
        self.frame_27.setGeometry(QtCore.QRect(230, 150, 101, 20))
        self.frame_27.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_27.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.label_t27 = QtWidgets.QLabel(self.frame_27)
        self.label_t27.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t27.setFont(font)
        self.label_t27.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t27.setStyleSheet("")
        self.label_t27.setObjectName("label_t27")
        self.label_26 = QtWidgets.QLabel(self.frame_27)
        self.label_26.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_26.setStyleSheet("")
        self.label_26.setObjectName("label_26")
        self.frame_21 = QtWidgets.QFrame(self.frame_Key)
        self.frame_21.setGeometry(QtCore.QRect(230, 30, 101, 20))
        self.frame_21.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.label_t21 = QtWidgets.QLabel(self.frame_21)
        self.label_t21.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t21.setFont(font)
        self.label_t21.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t21.setStyleSheet("")
        self.label_t21.setObjectName("label_t21")
        self.label_27 = QtWidgets.QLabel(self.frame_21)
        self.label_27.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_27.setStyleSheet("")
        self.label_27.setObjectName("label_27")
        self.frame_30 = QtWidgets.QFrame(self.frame_Key)
        self.frame_30.setGeometry(QtCore.QRect(230, 210, 101, 20))
        self.frame_30.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_30.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.label_t30 = QtWidgets.QLabel(self.frame_30)
        self.label_t30.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t30.setFont(font)
        self.label_t30.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t30.setStyleSheet("")
        self.label_t30.setObjectName("label_t30")
        self.label_28 = QtWidgets.QLabel(self.frame_30)
        self.label_28.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_28.setStyleSheet("")
        self.label_28.setObjectName("label_28")
        self.frame_22 = QtWidgets.QFrame(self.frame_Key)
        self.frame_22.setGeometry(QtCore.QRect(230, 50, 101, 20))
        self.frame_22.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_22.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.label_t22 = QtWidgets.QLabel(self.frame_22)
        self.label_t22.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t22.setFont(font)
        self.label_t22.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t22.setStyleSheet("")
        self.label_t22.setObjectName("label_t22")
        self.label_29 = QtWidgets.QLabel(self.frame_22)
        self.label_29.setGeometry(QtCore.QRect(10, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_29.setStyleSheet("")
        self.label_29.setObjectName("label_29")
        self.frame_26 = QtWidgets.QFrame(self.frame_Key)
        self.frame_26.setGeometry(QtCore.QRect(230, 130, 101, 20))
        self.frame_26.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_26.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.label_t26 = QtWidgets.QLabel(self.frame_26)
        self.label_t26.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t26.setFont(font)
        self.label_t26.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t26.setStyleSheet("")
        self.label_t26.setObjectName("label_t26")
        self.label_30 = QtWidgets.QLabel(self.frame_26)
        self.label_30.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_30.setStyleSheet("")
        self.label_30.setObjectName("label_30")
        self.frame_24 = QtWidgets.QFrame(self.frame_Key)
        self.frame_24.setGeometry(QtCore.QRect(230, 90, 101, 20))
        self.frame_24.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_24.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.label_t24 = QtWidgets.QLabel(self.frame_24)
        self.label_t24.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t24.setFont(font)
        self.label_t24.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t24.setStyleSheet("")
        self.label_t24.setObjectName("label_t24")
        self.label_31 = QtWidgets.QLabel(self.frame_24)
        self.label_31.setGeometry(QtCore.QRect(10, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_31.setStyleSheet("")
        self.label_31.setObjectName("label_31")
        self.frame_29 = QtWidgets.QFrame(self.frame_Key)
        self.frame_29.setGeometry(QtCore.QRect(230, 190, 101, 20))
        self.frame_29.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_29.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.label_t29 = QtWidgets.QLabel(self.frame_29)
        self.label_t29.setGeometry(QtCore.QRect(45, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t29.setFont(font)
        self.label_t29.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t29.setStyleSheet("")
        self.label_t29.setObjectName("label_t29")
        self.label_32 = QtWidgets.QLabel(self.frame_29)
        self.label_32.setGeometry(QtCore.QRect(9, 3, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_32.setStyleSheet("")
        self.label_32.setObjectName("label_32")
        self.label_main_3 = QtWidgets.QLabel(self.frame_Key)
        self.label_main_3.setGeometry(QtCore.QRect(140, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_main_3.setFont(font)
        self.label_main_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_main_3.setStyleSheet("")
        self.label_main_3.setObjectName("label_main_3")
        self.pushButton_Horn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Horn.setEnabled(False)
        self.pushButton_Horn.setGeometry(QtCore.QRect(400, 340, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Horn.setFont(font)
        self.pushButton_Horn.setCheckable(True)
        self.pushButton_Horn.setObjectName("pushButton_Horn")
        self.pushButton_Check_Connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Check_Connect.setEnabled(False)
        self.pushButton_Check_Connect.setGeometry(QtCore.QRect(360, 27, 111, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Check_Connect.setFont(font)
        self.pushButton_Check_Connect.setObjectName("pushButton_Check_Connect")
        IP_Phone_Tester.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IP_Phone_Tester)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 18))
        self.menubar.setObjectName("menubar")
        IP_Phone_Tester.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IP_Phone_Tester)
        self.statusbar.setObjectName("statusbar")
        IP_Phone_Tester.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(IP_Phone_Tester)
        self.action.setObjectName("action")

        self.retranslateUi(IP_Phone_Tester)
        QtCore.QMetaObject.connectSlotsByName(IP_Phone_Tester)

    def retranslateUi(self, IP_Phone_Tester):
        _translate = QtCore.QCoreApplication.translate
        IP_Phone_Tester.setWindowTitle(_translate("IP_Phone_Tester", "Тестер плат IP телефонов"))
        self.label_change_port.setText(_translate("IP_Phone_Tester", "Выбор порта"))
        self.pushButton_open_COM.setText(_translate("IP_Phone_Tester", "Открыть порт"))
        self.pushButton_Speak.setText(_translate("IP_Phone_Tester", "Спикерфон"))
        self.pushButton_close_COM.setText(_translate("IP_Phone_Tester", "Закрыть порт"))
        self.pushButton_Hendset.setText(_translate("IP_Phone_Tester", "Телефонная трубка"))
        self.pushButton_Mic.setText(_translate("IP_Phone_Tester", "Микрофон в корпусе"))
        self.checkBox_1.setText(_translate("IP_Phone_Tester", "- 1"))
        self.label_main.setText(_translate("IP_Phone_Tester", "Светодиоды"))
        self.checkBox_2.setText(_translate("IP_Phone_Tester", "- 2"))
        self.checkBox_3.setText(_translate("IP_Phone_Tester", "- 3"))
        self.checkBox_4.setText(_translate("IP_Phone_Tester", "- 4"))
        self.checkBox_5.setText(_translate("IP_Phone_Tester", "- 5"))
        self.checkBox_6.setText(_translate("IP_Phone_Tester", "- 6"))
        self.checkBox_7.setText(_translate("IP_Phone_Tester", "- 7"))
        self.checkBox_8.setText(_translate("IP_Phone_Tester", "- 8"))
        self.checkBox_9.setText(_translate("IP_Phone_Tester", "- 9"))
        self.checkBox_10.setText(_translate("IP_Phone_Tester", "- 10"))
        self.checkBox_11.setText(_translate("IP_Phone_Tester", "- 11"))
        self.checkBox_12.setText(_translate("IP_Phone_Tester", "- 12"))
        self.checkBox_13.setText(_translate("IP_Phone_Tester", "- 13"))
        self.checkBox_14.setText(_translate("IP_Phone_Tester", "- 14"))
        self.checkBox_15.setText(_translate("IP_Phone_Tester", "- 15"))
        self.checkBox_16.setText(_translate("IP_Phone_Tester", "- 16"))
        self.checkBox_17.setText(_translate("IP_Phone_Tester", "- 17"))
        self.checkBox_18.setText(_translate("IP_Phone_Tester", "- 18"))
        self.checkBox_19.setText(_translate("IP_Phone_Tester", "- 19"))
        self.checkBox_20.setText(_translate("IP_Phone_Tester", "- 20"))
        self.checkBox_21.setText(_translate("IP_Phone_Tester", "- 21"))
        self.checkBox_22.setText(_translate("IP_Phone_Tester", "- 22"))
        self.checkBox_23.setText(_translate("IP_Phone_Tester", "- 23"))
        self.checkBox_24.setText(_translate("IP_Phone_Tester", "- 24"))
        self.checkBox_25.setText(_translate("IP_Phone_Tester", "- 25"))
        self.checkBox_26.setText(_translate("IP_Phone_Tester", "- 26"))
        self.checkBox_27.setText(_translate("IP_Phone_Tester", "- 27"))
        self.checkBox_28.setText(_translate("IP_Phone_Tester", "- 28"))
        self.checkBox_29.setText(_translate("IP_Phone_Tester", "- 29"))
        self.checkBox_30.setText(_translate("IP_Phone_Tester", "- 30"))
        self.pushButton_Next_LED.setText(_translate("IP_Phone_Tester", "Включить следующий"))
        self.pushButton_LED_1.setText(_translate("IP_Phone_Tester", "Красный"))
        self.pushButton_LED_2.setText(_translate("IP_Phone_Tester", "Зеленый"))
        self.radioButton_Perm.setText(_translate("IP_Phone_Tester", "Постоянно"))
        self.radioButton_Blink.setText(_translate("IP_Phone_Tester", "Моргание"))
        self.label_t9.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_9.setText(_translate("IP_Phone_Tester", "№9"))
        self.label_t4.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_4.setText(_translate("IP_Phone_Tester", "№4"))
        self.label_t8.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_8.setText(_translate("IP_Phone_Tester", "№8"))
        self.label_t3.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_3.setText(_translate("IP_Phone_Tester", "№3"))
        self.label_t1.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_1.setText(_translate("IP_Phone_Tester", "№1"))
        self.label_t10.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_10.setText(_translate("IP_Phone_Tester", "№10"))
        self.label_t6.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_6.setText(_translate("IP_Phone_Tester", "№6"))
        self.label_t2.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_2.setText(_translate("IP_Phone_Tester", "№2"))
        self.label_t5.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_5.setText(_translate("IP_Phone_Tester", "№5"))
        self.label_t7.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_7.setText(_translate("IP_Phone_Tester", "№7"))
        self.label_t13.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_13.setText(_translate("IP_Phone_Tester", "№13"))
        self.label_t18.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_18.setText(_translate("IP_Phone_Tester", "№18"))
        self.label_t11.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_11.setText(_translate("IP_Phone_Tester", "№11"))
        self.label_t19.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_19.setText(_translate("IP_Phone_Tester", "№19"))
        self.label_t15.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_15.setText(_translate("IP_Phone_Tester", "№15"))
        self.label_t12.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_12.setText(_translate("IP_Phone_Tester", "№12"))
        self.label_t14.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_14.setText(_translate("IP_Phone_Tester", "№14"))
        self.label_t16.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_16.setText(_translate("IP_Phone_Tester", "№16"))
        self.label_t20.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_20.setText(_translate("IP_Phone_Tester", "№20"))
        self.label_t17.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_17.setText(_translate("IP_Phone_Tester", "№17"))
        self.label_t23.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_23.setText(_translate("IP_Phone_Tester", "№23"))
        self.label_t28.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_24.setText(_translate("IP_Phone_Tester", "№28"))
        self.label_t25.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_25.setText(_translate("IP_Phone_Tester", "№25"))
        self.label_t27.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_26.setText(_translate("IP_Phone_Tester", "№27"))
        self.label_t21.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_27.setText(_translate("IP_Phone_Tester", "№21"))
        self.label_t30.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_28.setText(_translate("IP_Phone_Tester", "№30"))
        self.label_t22.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_29.setText(_translate("IP_Phone_Tester", "№22"))
        self.label_t26.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_30.setText(_translate("IP_Phone_Tester", "№26"))
        self.label_t24.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_31.setText(_translate("IP_Phone_Tester", "№24"))
        self.label_t29.setText(_translate("IP_Phone_Tester", "отжата"))
        self.label_32.setText(_translate("IP_Phone_Tester", "№29"))
        self.label_main_3.setText(_translate("IP_Phone_Tester", "Кнопки"))
        self.pushButton_Horn.setText(_translate("IP_Phone_Tester", "Динамик"))
        self.pushButton_Check_Connect.setText(_translate("IP_Phone_Tester", "Проверка связи"))
        self.action.setText(_translate("IP_Phone_Tester", "Закрыть"))

